### ISSUE TITLE
https://github.com/googlearchive/code-prettify

### ISSUE THREAD

**Issue by dlemaignent** [webjars/webjars-classic#7]
Is it possible to add "official" google code prettify has webjar ?

https://github.com/googlearchive/code-prettify

Thanks

**Comment by jamesward** [comment]
I think this Classic WebJar already exists:
https://github.com/webjars/prettify

Let me know if you need a new version or if that WebJar is different from what you need.

**Comment by dlemaignent** [comment]
Thank you, indeed I managed to use the classic repository. Best regards.
