### ISSUE TITLE
PrimeUI and other members of the PrimeFaces family

### ISSUE THREAD

**Issue by ajspadial** [webjars/webjars-classic#9]
May you add webjars for PrimeUI, PrimeFaces and other members of the PrimeFaces familiy?

Thank you

[https://github.com/primefaces/primeui](https://github.com/primefaces/primeui)

**Comment by jamesward** [comment]
Can you use the existing NPM WebJars for this?

**Comment by ajspadial** [comment]
Sure. I apologize for my poor search skills. Now I can see it, but can't say why I couldn't find it that day. 

Thank you.
